# install.packages("dplyr")
# install.packages("readr")
# install.packages("data.table")
# install.packages("stringr")
# install.packages("data.tree")
# install.packages("purrr")
# install.packages("DiagrammeR")
# install.packages("ggformula")
# install.packages("permutations")

require(dplyr)
require(data.table)
require(stringr)
require(readr)
require(purrr)
require(data.tree)
require(ggformula)
require(permutations)
require(pracma)

options(digits=22)
